[git]
conventional_commits = true
protect_breaking_commits = true
commit_parsers = [
    { message = "^fix", group = "Bug Fixes"},
    { message = "^feat", group = "Features"},
    { message = "^chore", skip = true},
    { message = "^Merging", skip = true },
]

[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}\
{% else %}\
    ## Unreleased\
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}\
        - {{ commit.message | upper_first }}
    {% endfor %}\
{% endfor %}\n
{% if commits | filter(attribute="breaking", value=true) %}\
### Breaking change(s)
{% for commit in commits %}
    {% if commit.breaking %}\
        - {{ commit.breaking_description | upper_first }}
    {% endif %}\
{% endfor %}\n
{% endif %}\

"""
