[git]
conventional_commits = true
commit_parsers = [
    { message = "^fix", group = "Bug Fixes"},
    { message = "^feat", group = "Features"},
    { message = "^deps", group = "Upgrades"},
    { message = "^chore", skip = true},
]
protect_breaking_commits = true
filter_commits = true

[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    # {{ version | trim_start_matches(pat="v") }}
{% else %}\
    # Unreleased
{% endif %}\

{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
    ## {{ group | upper_first }}
    {% for commit in commits %}\
        - {{ commit.message | upper_first }}
        {% if commit.body %}\
            {{ commit.body }}\
        {% endif %}\
    {% endfor %}\
{% endfor %}

{% set breakings = commits | filter(attribute="breaking", value=true) %}\
{% if breakings %}\
    ## Breaking change(s)
    {% for commit in breakings %}\
        - {{ commit.breaking_description | upper_first }}
    {% endfor %}\n
{% endif %}\
"""
