[git]
conventional_commits = true
# Hijack scope attribute below to prevent chore commits to be listed. We cannot
# skip them explicitelly, otherwise their breaking change would also be skipped.
commit_parsers = [
    { message = "^fix", group = "Bug Fixes", scope = "keep"},
    { message = "^feat", group = "Features", scope = "keep"},
    { message = "^deps", group = "Upgrades", scope = "keep"},
    { message = "^chore", scope = "skip"},
]
protect_breaking_commits = true
filter_commits = true

[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    # {{ version | trim_start_matches(pat="v") }}
{% else %}\
    # Unreleased
{% endif %}\

{% for group, commits in commits | filter(attribute="merge_commit", value=false)
| filter(attribute="scope", value="keep") | group_by(attribute="group") %}
    ## {{ group | upper_first }}
    {% for commit in commits %}\
        - {{ commit.message | upper_first }}
        {% if commit.body %}\
            {{ commit.body }}\
        {% endif %}\
    {% endfor %}\
{% endfor %}\

{% set breakings = commits | filter(attribute="breaking", value=true) %}\
{% if breakings %}
    ## Breaking change(s)
    {% for commit in breakings %}\
        - {{ commit.breaking_description | upper_first }}
    {% endfor %}\n
{% endif %}\
"""
